export const ADD_EXERCISE = "ADD_EXERCISE";
export const DELETE_EXERCISE = "DELETE_EXERCISE";
export const ADD_CATEGORY = "ADD_CATEGORY";
export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const ADD_ROUTINE = "ADD_ROUTINE";
export const DELETE_ROUTINE = "DELETE_ROUTINE";
export const UPDATE_EXERCISE_FORM = "UPDATE_EXERCISE_FORM";
export const SET_SELECTED_ITEM = "SET_DETAIL_ITEM";
